Print network and time info when the board starts
GoogleCloudPlatform/iot-core-micropython pull request #3
Opened 2019-07-04 07:23 UTC by ferrarimarco

Printing network info and the current time (when setting that up) is useful for debugging purposes. Due to the "example" nature of this project I think it's useful to show this when a user is moving first steps with a ESP32 board.

2019-07-04 16:47 UTC, gguuss requested changes

2019-07-04 16:47 UTC, gguuss commented on main.py
> +    print('network config:', sta_if.ifconfig())
Prefer string format over concatenation:

```python
print('network config: {}'.format(sta_if.ifconfig()))
```

2019-07-04 16:47 UTC, gguuss commented on main.py
> +    print('current time:', utime.localtime())
```python
print('current time: {}'.format(utime.localtime()))
```

2019-07-05 09:38 UTC, ferrarimarco commented on main.py
> +    print('network config:', sta_if.ifconfig())
done

2019-07-05 09:38 UTC, ferrarimarco commented on main.py
> +    print('current time:', utime.localtime())
done

2019-07-05 09:39 UTC, ferrarimarco commented
I've addressed your comments and rebased on the latest master

2019-07-05 09:39 UTC, ferrarimarco commented
Thx @gguuss !

2019-07-06 18:11 UTC, merged